name: Build Release


on:
  schedule:
   - cron: '0 21 * * 6' # 每周六5点
  workflow_dispatch: # 手动触发

permissions: write-all


jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          - aarch64_cortex-a72
          - aarch64_generic
          - x86_64
        sdk:
          - openwrt-23.05
          - openwrt-24.10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        uses: sbwml/openwrt-gh-action-sdk@go1.23
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: luci-app-advancedplus luci-app-homeproxy luci-app-wolplus luci-app-adguardhome luci-app-passwall
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-${{ matrix.sdk }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.{ipk,apk}

      - name: Create compress files
        run: |
          tar -zcvf packages-${{ matrix.sdk }}-${{ matrix.arch }}.tar.gz -C bin/packages/${{ matrix.arch }}/ packages_ci

      - name: Generate Tag Name
        id: generate_tag
        run: |
          DATE=$(date +'%Y%m%d')
          echo "TAG_NAME=v${DATE}" >> $GITHUB_ENV
          
      - name: Upload packages
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "packages-${{ matrix.sdk }}-${{ matrix.arch }}.tar.gz"
