name: Sync Upstreams

on:
  schedule:
    - cron: '0 20 * * *' # 每天运行
  workflow_dispatch: # 手动触发

permissions: write-all

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 检出当前 Fork 仓库
      - name: Checkout Fork Repository
        uses: actions/checkout@v3

      # 设置 Git 用户信息
      - name: Set Git User
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "<github-actions[bot]@users.noreply.github.com>"
          
      # 通用同步函数
      - name: Sync Repositories
        run: |
          sync_repo() { 
              LOCAL_DIR=$1
              REMOTE_REPO=$2
              REMOTE_SUBDIRS=$3
              BRANCH_NAME=${4:-main}
              
              echo "Syncing $REMOTE_REPO -> $LOCAL_DIR"
          
              # 创建临时目录
              TEMP_DIR=$(mktemp -d)
              echo "Temporary directory: $TEMP_DIR"
          
              # 克隆远程仓库
              git clone --depth 1 -b "$BRANCH_NAME" "$REMOTE_REPO" "$TEMP_DIR"
          
              # 如果只有一个子目录，直接同步
              if [[ $(echo "$REMOTE_SUBDIRS" | tr ',' '\n' | wc -l) -eq 1 ]]; then
                  REMOTE_SUBDIR="$REMOTE_SUBDIRS"
                  # 创建目标子目录
                  mkdir -p "$LOCAL_DIR"
                  rsync -a --delete --exclude='.git' "$TEMP_DIR/$REMOTE_SUBDIR/" "$LOCAL_DIR/"
              else
                  # 遍历多个子目录
                  for REMOTE_SUBDIR in $(echo "$REMOTE_SUBDIRS" | tr ',' '\n'); do
                      # 创建目标子目录
                      mkdir -p "$LOCAL_DIR/$REMOTE_SUBDIR"
                      # 同步指定子目录
                      rsync -a --delete --exclude='.git' "$TEMP_DIR/$REMOTE_SUBDIR/" "$LOCAL_DIR/$REMOTE_SUBDIR/"
                  done
              fi

              # 提交更改
              git add "$LOCAL_DIR"
              if [ -n "$(git status --porcelain)" ]; then
                  git commit -m "Sync Upstreams $LOCAL_DIR"
              fi
              
              # 清理临时目录
              rm -rf "$TEMP_DIR"
          }
          # 调用同步函数
          sync_repo luci-app-advancedplus https://github.com/sirpdboy/luci-app-advancedplus.git ""
          sync_repo luci-app-timecontrol https://github.com/sirpdboy/luci-app-timecontrol.git "luci-app-nft-timecontrol" "main"
          sync_repo luci-app-wolplus https://github.com/sundaqiang/openwrt-packages.git "luci-app-wolplus" "master"
          sync_repo luci-app-homeproxy https://github.com/VIKINGYFY/homeproxy.git "" "main"
          sync_repo luci-app-adguardhome https://github.com/kenzok8/small-package.git "luci-app-adguardhome" "main"
          sync_repo luci-app-passwall https://github.com/xiaorouji/openwrt-passwall.git luci-app-passwall
          sync_repo luci-app-socat https://github.com/sbwml/openwrt_pkgs.git luci-app-socat
          sync_repo luci-app-openclash https://github.com/vernesong/OpenClash.git "luci-app-openclash" "master"
          sync_repo luci-theme-argon-pkgs https://github.com/sbwml/luci-theme-argon.git "luci-theme-argon,luci-app-argon-config" "openwrt-24.10" 
          sync_repo luci-app-alist-pkgs https://github.com/sbwml/luci-app-alist.git "luci-app-alist,alist"
          sync_repo luci-app-nikki-pkgs https://github.com/nikkinikki-org/OpenWrt-nikki "luci-app-nikki,nikki"
          #sync_repo luci-app-mihomo-pkgs https://github.com/morytyann/OpenWrt-mihomo "luci-app-mihomo,mihomo"
          #sync_repo luci-theme-argon-pkgs/luci-theme-argon https://github.com/jerrykuku/luci-theme-argon.git "" "master"
          #sync_repo luci-theme-argon-pkgs/luci-app-argon-config https://github.com/jerrykuku/luci-app-argon-config.git "" "master"
          sync_repo luci-app-onliner https://github.com/ftkey/luci-app-onliner.git ""
          sync_repo ddns-scripts-aliyun https://github.com/sbwml/openwrt_pkgs.git ddns-scripts-aliyun
          sync_repo luci-app-mosdns-pkgs https://github.com/sbwml/luci-app-mosdns.git "luci-app-mosdns,mosdns,v2dat" "v5" 
          sync_repo luci-app-openlist2-pkgs https://github.com/sbwml/luci-app-openlist2.git "luci-app-openlist2,openlist2"
          sync_repo luci-theme-kucat https://github.com/sirpdboy/luci-theme-kucat.git "luci-theme-kucat" "js" 
          sync_repo luci-app-lucky-pkgs https://github.com/sirpdboy/luci-app-lucky.git "luci-app-lucky,lucky" "main"
          sync_repo luci-app-bandix-pkgs/bandix https://github.com/timsaya/openwrt-bandix.git "" "main"
          sync_repo luci-app-bandix-pkgs/luci-app-bandix https://github.com/timsaya/luci-app-bandix.git "" "main"



          
      # 推送更改到当前 Fork 仓库
      - name: Push Changes
        run: |
          git push origin main
